baseURL = "https://soab1.github.io/profile.me/"
title = "Masaya's Profile"
theme = "hugo-coder"
languageCode = "en"
defaultContentLanguage = "en"

paginate = 20

pygmentsStyle = "bw"
pygmentsCodeFences = true
pygmentsCodeFencesGuessSyntax = true

disqusShortname = "yourdiscussshortname"

[params]
  author = "Masaya Kumata"
  description = "Infrastructure Engineer's blog."
  keywords = "blog,infrastructure,engineer"
  avatarURL = "profile.jpg"

  favicon_16 = "favicon-16x16.png"
  favicon_32 = "favicon-32x32.png"

  since = "2020"

  enableEmoji = true

  colorScheme = "auto"
  hidecolorschemetoggle = false

  customCSS = []
  customSCSS = []
  customJS = []

[params.csp]
  childsrc = ["'self'"]
  fontsrc = ["'self'", "https://fonts.gstatic.com", "https://cdn.jsdelivr.net/"]
  formaction = ["'self'"]
  framesrc = ["'self'"]
  imgsrc = ["'self'"]
  objectsrc = ["'none'"]
  stylesrc = [
    "'self'",
    "'unsafe-inline'",
    "https://fonts.googleapis.com/",
    "https://cdn.jsdelivr.net/"
  ]
  scriptsrc = [
    "'self'",
    "'unsafe-inline'",
    "https://www.google-analytics.com",
    "https://cdn.jsdelivr.net/"
  ]
  prefetchsrc = ["'self'"]
  connectsrc = ["'self'", "https://www.google-analytics.com"]

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"
  author = "authors"

[[params.social]]
  name = "Github"
  icon = "fa fa-2x fa-github"
  weight = 1
  url = "https://github.com/SoaB1/"

[[params.social]]
  name = "Twitter"
  icon = "fa fa-2x fa-twitter"
  weight = 3
  url = "https://twitter.com/SoaB_cs/"

[languages.en]
  languageName = ":us:"

[[languages.en.menu.main]]
  name = "About"
  weight = 1
  url = "about/"

[[languages.en.menu.main]]
  name = "Blog"
  weight = 2
  url = "posts/"

[[languages.en.menu.main]]
  name = "Contact"
  weight = 5
  url = "contact/"

[languages.ja-jp]
  languageName = ":jp:"
# title = "マサヤ クマタ"

[languages.ja-jp.params]
  description = "インフラエンジニアのブログです。"

[[languages.ja-jp.menu.main]]
  name = "アバウト"
  weight = 1
  url = "about/"

[[languages.ja-jp.menu.main]]
  name = "ブログ"
  weight = 2
  url = "posts/"

[[languages.ja-jp.menu.main]]
  name = "コンタクト"
  weight = 5
  url = "contact/"