baseURL: "https://soab1.github.io/profile.me/"
canonifyurls: false
publishDir: "content"
title: Masaya
paginate: 5
theme: PaperMod

enableEmoji: true
enableRobotsTXT: true

buildDrafts: false
buildFuture: false
buildExpired: false

minify:
  disableXML: true
  minifyOutput: true

params:
  title: Masaya.me
  description: "Infrastructure Engineer's blog."
  keywords: [Blog, Portfolio]
  author: Masaya Kumata
  # author: ["Me", "You"] # multiple authors
  images: ["profile.jpg"]
  DateFormat: "January 2, 2006"
  defaultTheme: auto # dark, light
  disableThemeToggle: false

  ShowReadingTime: true
  ShowShareButtons: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true

  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: false
  hidemeta: false
  hideSummary: false
  showtoc: false
  tocopen: false

  assets:
    # disableHLJS: true # to disable highlight.js
    # disableFingerprinting: true
    favicon: "https://i.imgur.com/x0Nsqmu.png"
    favicon16x16: "https://i.imgur.com/ooambAU.png"
    favicon32x32: "https://i.imgur.com/mhpE7jh.png"
    apple_touch_icon: "https://i.imgur.com/mhpE7jh.png"
    safari_pinned_tab: "https://i.imgur.com/mhpE7jh.png"

  label:
    text: "🏠 Home"
    # icon: Thinking_Face_Emoji_large.png
    iconHeight: 35

  # profile-mode
  profileMode:
    enabled: true # needs to be explicitly set
    title: "I'm Masaya"
    subtitle: "A Infrastructure engineer."
    imageUrl: "profile.jpg"
    imageWidth: 200
    imageHeight: 200
    imageTitle: my image
    # buttons:
    #     - name: Posts
    #       url: posts

  socialIcons:
    - name: twitter
      url: "https://twitter.com/SoaB_cs"
    - name: github
      url: "https://github.com/SoaB1"

  cover:
    hidden: true # hide everywhere but not in structured data
    hiddenInList: true # hide on list pages and home
    hiddenInSingle: true # hide on single page

  editPost:
    URL: "https://github.com/SoaB1/profile.me/content"
    Text: "Suggest Changes" # edit text
    appendFilePath: true # to append file path to Edit link

  # for search
  # https://fusejs.io/api/options.html
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]
menu:
  main:
    - identifier: posts
      name: posts
      url: posts
      weight: 5
    - identifier: profile
      name: profile
      url: fixed/profile
      weight: 10
    - name: works
      url: fixed/works
      weight: 15
    - name: search
      url: search/
      weight: 20
    - identifier: tags
      name: tags
      url: tags/
      weight: 25
# Read: https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#using-hugos-syntax-highlighter-chroma
# pygmentsUseClasses: true
# markup:
#     highlight:
#         # anchorLineNos: true
#         codeFences: true
#         guessSyntax: true
#         lineNos: true
#         style: monokai
